Rename the logos by size

diff --git a/browser-extensions/firefox/make-xpi b/browser-extensions/firefox/make-xpi
--- a/browser-extensions/firefox/make-xpi
+++ b/browser-extensions/firefox/make-xpi
@@ -55,6 +55,10 @@ for file in `find build -type f | xargs`; do
 done
 
 pushd build > /dev/null
+if [ $? -ne 0 ]; then
+    echo "*** ERROR"
+    exit 1
+fi
 
 #echo "Building '${jarName}.jar'..."
 #cd chrome > /dev/null
