firefox/make-xpi     Make sure we don't replace '.' in the string of the jsonRpc url.
firefox/chrome/resource/connexions.js
    Move shared state to this resource.

firefox/chrome/content/options.js
    Upon initial load, fire connexions.retrieveUser() -- if we attempt to
    retrieve too quickly (i.e. as soon as the connexions resource loads) things
    like cookies are not yet ready.

firefox/chrome/content/connexions.js
    Simply attach to the shared resource.

firefox/chrome/content/ff-overlay.js
firefox/chrome/content/ff-sidebar.js
    File comments

firefox/makefile
    Simple makefile

diff --git a/branches/zend/browser-extensions/firefox/make-xpi b/branches/zend/browser-extensions/firefox/make-xpi
--- a/branches/zend/browser-extensions/firefox/make-xpi
+++ b/branches/zend/browser-extensions/firefox/make-xpi
@@ -5,22 +5,29 @@
 config='../../application/configs/application.ini'
 
 firefox=`grep '^extensions\.firefox\.' "${config}" | \
-	   sed 's/^extensions\.firefox\.//g;s/[ ]*=[ ]*/=/g;'`
+       sed 's/^extensions\.firefox\.//g;s/[ ]*=[ ]*/=/g;'`
 eval $firefox;
 
 jsonRpc=`grep '^api\.jsonRpc\.' "${config}" | \
-	   sed 's/^api\.//g;s/\./_/g;s/[ ]*=[ ]*/=/g;'`
+       sed 's/^api\.//g;s/jsonRpc\./jsonRpc_/g;s/[ ]*=[ ]*/=/g;'`
 eval $jsonRpc;
 
-if [ -z "$domain" -o -z "$cookieName" -o -z "$url" -o -z "$author" -o -z "$authorUrl" -o -z "$version" ]; then
-	echo "*** Missing one or more definitions from '${config}'"
-	echo "***	extensions.firefox.version"
-	echo "***	extensions.firefox.domain"
-	echo "***	extensions.firefox.cookieName"
-	echo "***	extensions.firefox.url"
-	echo "***	extensions.firefox.author"
-	echo "***	extensions.firefox.authorUrl"
-	exit 1
+if [ -z "$domain" -o -z "$url" -o -z "$author" -o -z "$authorUrl" -o -z "$version" ]; then
+    echo "*** Missing one or more definitions from '${config}'"
+    echo "***   extensions.firefox.version      [ ${version} ]"
+    echo "***   extensions.firefox.domain       [ ${domain} ]"
+    echo "***   extensions.firefox.url          [ ${url} ]"
+    echo "***   extensions.firefox.author       [ ${author} ]"
+    echo "***   extensions.firefox.authorUrl    [ ${authorUrl} ]"
+    exit 1
+fi
+
+if [ -z "$jsonRpc_version" -o -z "$jsonRpc_url" -o -z "$jsonRpc_transport" ]; then
+    echo "*** Missing one or more JsonRpc definitions from '${config}'"
+    echo "***   api.jsonRpc.version      [ ${jsonRpc_version} ]"
+    echo "***   api.jsonRpc.url          [ ${jsonRpc_url} ]"
+    echo "***   api.jsonRpc.transport    [ ${jsonRpc_transport} ]"
+    exit 1
 fi
 
 jarName="connexions"
@@ -36,16 +43,15 @@ cp -R defaults build
 rm -rf `find build -name '*svn*' | xargs`
 
 # Replace all occurrences of
-#	%VERSION%, %DOMAIN%, %URL%, %AUTHOR%, and %AUTHOR_URL%
+#   %VERSION%, %DOMAIN%, %URL%, %AUTHOR%, and %AUTHOR_URL%
 #
 # As well as JsonRpc related replacables:
-#	%JSONRPC_VERSION%, %JSONRPC_URL%, %JSONRPC_TRANSPORT%
+#   %JSONRPC_VERSION%, %JSONRPC_URL%, %JSONRPC_TRANSPORT%
 #
 #
 # with the matching values from the configuration file.
 sedCmd="s#%VERSION%#${version}#g"
 sedCmd="${sedCmd};s#%DOMAIN%#${domain}#g"
-sedCmd="${sedCmd};s#%COOKIENAME%#${cookieName}#g"
 sedCmd="${sedCmd};s#%URL%#${url}#g"
 sedCmd="${sedCmd};s#%AUTHOR%#${author}#g"
 sedCmd="${sedCmd};s#%AUTHOR_URL%#${authorUrl}#g"
@@ -56,7 +62,6 @@ sedCmd="${sedCmd};s#%JSONRPC_TRANSPORT%#${jsonRpc_transport}#g"
 echo "Replacing variables: "
 echo " VERSION    [ ${version} ]"
 echo " DOMAIN     [ ${domain} ]"
-echo " COOKIENAME [ ${cookieName} ]"
 echo " URL        [ ${url} ]"
 echo " AUTHOR     [ ${author} ]"
 echo " AUTHOR_URL [ ${authorUrl} ]"
@@ -66,10 +71,10 @@ echo "  URL       [ ${jsonRpc_url} ]"
 echo "  TRANSPORT [ ${jsonRpc_transport} ]"
 
 for file in `find build -type f | xargs`; do
-	#echo ">> ${file}..."
-	sed -e "${sedCmd}" "${file}" > "${file}.tmp"
-	mv "${file}.tmp" "${file}"
-	#echo ""
+    #echo ">> ${file}..."
+    sed -e "${sedCmd}" "${file}" > "${file}.tmp"
+    mv "${file}.tmp" "${file}"
+    #echo ""
 done
 
 pushd build > /dev/null
